# Jekyll will exclude these files during compilation
exclude:
  - CONTRIBUTING.md
  - README.md
  - TERMS.md
  - todo.md
  - front
  - node_modules
  - bower_components
  - bower.json
  - package.json
  - LICENSE
  - salt
  - Vagrantfile

# Whether or not to include docs that are marked as preview
includePreviews: true

# Markdown parsing configuration
markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: true

# All email links will use this variable
email: jared.tomeck@kitware.com?subject=Kitware UI Library

# Repository information, which is used for links like "View on Github"
repository:
  name: jtomeck/kwui_library
  url: https://github.com/jtomeck/kwui_library

# List of collections
collections:
  apps:
    output: true

# The categories for the side navigation. These correspond to the folders under the /apps/appname folder
doctypes:
  - foundation
  - components
